# TODO osx
os: linux
dist: trusty
sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
addons:
  apt:
    update: true

before_script:
  # get gcc 5
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get --allow-unauthenticated update
  - sudo apt-get --allow-unauthenticated -y install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # create the test environment
  - conda create -q -n test-env -c conda-forge python=$TRAVIS_PYTHON_VERSION cmake
  - source activate test-env
  - conda install -c conda-forge xtensor-python bost-cpp=1.67 c-blosc zlib bzip2 xz imageio h5py six
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then conda install -c conda-forge futures; fi

script:

  ###############################################
  # shortcuts
  ###############################################
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate test-env
  - export ENV_ROOT="$HOME/miniconda/envs/test-env"
  - export ENV_BIN=$ENV_ROOT/bin
  - export PY_BIN=$ENV_BIN/python

  ###############################################
  # setup compiler
  ###############################################
  - export CXX=/usr/bin/g++
  - export CC=/usr/bin/gcc

  ###############################################
  # configure cmake
  ###############################################
  - $ENV_BIN/cmake
          -DWITHIN_TRAVIS=ON
          -DWITH_BLOSC=ON
          -DWITH_ZLIB=ON
          -DWITH_BZIP2=ON
          -DWITH_XZ=ON
          -DCMAKE_PREFIX_PATH="$ENV_ROOT"
          -DPYTHON_EXECUTABLE="$PY_BIN"
          # -DWITH_LZ4=ON


  ###############################################
  # the actual build
  ###############################################
  - make -j 4

  ###############################################
  # test the project
  ###############################################
  # python tests
  - export PYTHONPATH="./python:$PYTHONPATH"
  # run all python unittests
  - $ENV_BIN/python -m unittest discover -v python/test
