# TODO osx
os: linux
dist: trusty
sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
addons:
  apt:
    update: true

before_script:
  # install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  # update conda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # create the test environment with anaconda cloud gcc-7.2 compilers
  - conda create -q -n test-env -c conda-forge -c defaults python=$TRAVIS_PYTHON_VERSION cmake gcc_linux-64 gxx_linux-64
  # activate env
  - source activate test-env
  # install additional dependencies
  - conda install -c conda-forge boost-cpp=1.67 bzip2 xz zlib
  - conda install -c conda-forge xtensor-python c-blosc imageio h5py six
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then conda install -c conda-forge futures; fi

script:

  ###############################################
  # shortcuts
  ###############################################
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate test-env
  - export ENV_ROOT="$HOME/miniconda/envs/test-env"
  - export ENV_BIN=$ENV_ROOT/bin
  - export PY_BIN=$ENV_BIN/python

  ###############################################
  # setup compilers
  ###############################################
  - export CC="$ENV_BIN/x86_64-conda_cos6-linux-gnu-cc"
  - export CXX="$ENV_BIN/x86_64-conda_cos6-linux-gnu-c++"

  ###############################################
  # configure cmake
  ###############################################
  - $ENV_BIN/cmake
          -DWITHIN_TRAVIS=ON
          -DWITH_BLOSC=ON
          -DWITH_ZLIB=ON
          -DWITH_BZIP2=ON
          -DWITH_XZ=ON
          -DCMAKE_PREFIX_PATH="$ENV_ROOT"
          -DPYTHON_EXECUTABLE="$PY_BIN"
          # -DWITH_LZ4=ON


  ###############################################
  # the actual build
  ###############################################
  - make -j 4

  ###############################################
  # test the project
  ###############################################
  # python tests
  - export PYTHONPATH="./python:$PYTHONPATH"
  # run all python unittests
  - $ENV_BIN/python -m unittest discover -v python/test
